{% set version = "0.1.0" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: jupyterlite-pyodide-lock
  version: {{ version }}

source:
  - folder: jupyterlite-pyodide-lock
    url: https://pypi.org/packages/source/j/jupyterlite-pyodide-lock/jupyterlite_pyodide_lock-{{ version }}.tar.gz
    sha256: 4b35bb94f95982f18f681eed3dea17bf0af27363c39a31b084d59a1b00ecfbe2
  - folder: jupyterlite-pyodide-lock-webdriver
    url: https://pypi.org/packages/source/j/jupyterlite-pyodide-lock-webdriver/jupyterlite_pyodide_lock_webdriver-{{ version }}.tar.gz
    sha256: 4fc3446a9b6a616b5e619e1ccf8002ad507c3c6a5cf27d0f5220183167199e98

build:
  number: 0
  noarch: python
  script:
    - cd jupyterlite-pyodide-lock
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - jupyter-pyodide-lock = jupyterlite_pyodide_lock.app:main

requirements:
  host:
    - flit-core >=3.9.0,<4.0.0
    - pip
    - python {{ python_min }}
  run:
    - jupyterlite-core >=0.3.0,<0.6.0
    - jupyterlite-pyodide-kernel >=0.3.1,<0.6.0
    - psutil >=6
    - pyodide-lock-with-wheel >=0.1.0a4,<0.2.0
    - python >={{ python_min }}
    - tornado >=6.1.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - jupyterlite_pyodide_lock
  commands:
    - pip check
    - jupyter-pyodide-lock --version
    - jupyter pyodide-lock --version
    - jupyter pyodide-lock --help

outputs:
  - name: jupyterlite-pyodide-lock

  - name: jupyterlite-pyodide-lock-webdriver
    build:
      noarch: python
      script:
        - cd jupyterlite-pyodide-lock-webdriver
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

    requirements:
      host:
        - flit-core >=3.9.0,<4.0.0
        - pip
        - python {{ python_min }}
      run:
        - {{ pin_subpackage("jupyterlite-pyodide-lock", max_pin="x.x.x") }}
        - python >={{ python_min }}
        - selenium >=4.19
    test:
      requires:
        - pip
      imports:
        - jupyterlite_pyodide_lock_webdriver
      commands:
        - pip check

    about:
      home: https://github.com/deathbeds/jupyterlite-pyodide-lock
      summary: |
        Create pre-solved environments for jupyterlite-pyodide-kernel with pyodide-lock and Selenium
      license: BSD-3-Clause
      license_file:
        - jupyterlite-pyodide-lock-webdriver/LICENSE
      doc_url: https://jupyterlite-pyodide-lock.rtfd.org

  - name: jupyterlite-pyodide-lock-with-firefox
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jupyterlite-pyodide-lock", max_pin="x.x.x") }}
        - firefox >=128
        - geckodriver
    test:
      requires:
        - pip
      commands:
        - pip check
        - jupyter pyodide-lock browsers
    about:
      home: https://github.com/deathbeds/jupyterlite-pyodide-lock
      summary: |-
        Create pre-solved environments for jupyterlite-pyodide-kernel with pyodide-lock and Firefox
      license: BSD-3-Clause
      license_file:
        - jupyterlite-pyodide-lock/LICENSE
      doc_url: https://jupyterlite-pyodide-lock.rtfd.org

  - name: jupyterlite-pyodide-lock-recommended
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jupyterlite-pyodide-lock-with-firefox", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-pyodide-lock", max_pin="x.x.x") }}
        - jupyterlite-core-with-contents
        - jupyterlite-core-with-lab
        - jupyterlite-core-with-libarchive
    test:
      requires:
        - pip
      commands:
        - pip check
        - jupyter pyodide-lock browsers
    about:
      home: https://github.com/deathbeds/jupyterlite-pyodide-lock
      summary: |-
        Create pre-solved environments for jupyterlite-pyodide-kernel with pyodide-lock and recommended packages
      license: BSD-3-Clause
      license_file:
        - jupyterlite-pyodide-lock/LICENSE
      doc_url: https://jupyterlite-pyodide-lock.rtfd.org

about:
  home: https://github.com/deathbeds/jupyterlite-pyodide-lock
  summary: Create pre-solved environments for jupyterlite-pyodide-kernel with pyodide-lock
  license: BSD-3-Clause
  license_file:
    - jupyterlite-pyodide-lock/LICENSE
  doc_url: https://jupyterlite-pyodide-lock.rtfd.org

extra:
  feedstock-name: jupyterlite-pyodide-lock
  recipe-maintainers:
    - bollwyvl
